version: '3.8'
services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true